### ISSUE TITLE
Multiple message blocks

### ISSUE THREAD

**Issue by Footrotflat** [aaw-team/fe_cookies#2]
Hallo Christian

Kompliment!
Hervorragende Extension, und soweit ich dies beurteilen kann, sauber programmiert!

Eine kleine Sache ist mir aufgefallen:
Im 'Frontend Cookies Management' kann man doch mehrere 'Message blocks' anlegen.
Der erste 'message block' habe ich in Deutsch angelegt, den zweiten in Englisch.
Der Englisch 'message block' erscheint jedoch nicht im 'Frontend Cookies Management'.

Wenn ich die Datensätze via 'List' ansehe, sind dies beide vorhanden.

Eine zweite kleine Sache ist mir noch aufgefallen ;-)
Ich möchte den 'Banner' nicht unten sondern oben.
Ich habe dies bei mir via CSS gelöst, einfach...
Cool wäre natürlich, wenn ihr dies per Definition zur Wahl stellen würdet.

Super Sache!
Danke.
Beste Grüsse aus dem Aargau ;-)
Patrick

**Comment by christianfutterlieb** [comment]
Hey Patrick

Danke für die Blumen und die Anregungen. Die Banner oben/unten Sache habe ich gerade eingbaut, siehe b64aba7cbeb1586431fee169678bb95e3ab66df4 (das war im css schon lange drin, nur gabs noch keine constants config). 

Die Sprach-Probleme schaue ich noch an.

**Comment by Footrotflat** [comment]
Super!
Danke und Gruss
