### ISSUE TITLE
Language menu / default setting

### ISSUE THREAD

**Issue by Footrotflat** [aaw-team/fe_cookies#3]
Hallo Christian

Habe nun Zeit gefunden die Version 0.4.0 bei mir einzuspielen und zu testen.

Habe wieder was kleines gefunden ;-)

Ich habe bei mir vier Sprachen installiert.
Deutsch = 0 = default
dann noch Englisch (1), Französisch (2) und Italienisch (3).

Im Frontend Cookies Management oben Button Language in dieses Menu wechseln.
Hier kann man ja den Accept-button etc. mit eigenem Text definieren - cool!

Die Übersetzungen (EN, FR, IT) funktionieren einwandfrei.
Nur bei der Default Sprache (alle drei Felder) wird der selbst definierte Text nicht übernommen. :-(

Beste Grüsse
Patrick

**Comment by christianfutterlieb** [comment]
Hi Patrick

Hast Du `mod.fe_cookies.languageManagement.defaultLanguageIsocode = de` im PageTSConfig (siehe https://docs.typo3.org/typo3cms/extensions/fe_cookies/Configuration/TSConfig/Index.html) gesetzt?

**Comment by Footrotflat** [comment]
Hallo Christian

Diesen Teil der Doku habe ich natürlich voll 'überlesen'.
Habe etwas Mühe bei mir dies in der Config PageTS zu definieren.
Jetzt habe ich es in ext_tables.php in der Extension fe_cookies angepasst und es funktioniert für den Backend-User.

Ich mache aber ein Fragezeichen in der 'Anwendung' für den Admin.

Der Admin kann die Übersetzungen im Language-Management definieren,
nur für die Default-Language geht es nicht.
Es ist ja nicht so, dass als Default Text EN statt DE (default) im FE angezeigt wird.
Sondern die neue Definition (vom Admin) wird gar nicht ausgegeben, dafür aber die Standarddefinition (auch DE). Hmm.

Anyway, besten Dank und Gruss
Patrick

**Comment by christianfutterlieb** [comment]
> Habe etwas Mühe bei mir dies in der Config PageTS zu definieren.

1. Klick auf das Weltkugel-Symbol der Rootpage im Seitenbaum => "Edit"
2. Im Tab "Resources" die Einstellungen im Feld "Page TSConfig" erfassen.

> Jetzt habe ich es in ext_tables.php in der Extension fe_cookies angepasst

Ändere **niemals** den Code einer Extension direkt, Deine Anpassungen werden beim nächsten Update ungefragt Überschrieben. Zum Erfassen der Page TSConfig, gehe so vor wie oben beschrieben oder lies mehr darüber in der Doku: https://docs.typo3.org/typo3cms/TSconfigReference/UsingSetting/Index.html

> Ich mache aber ein Fragezeichen in der 'Anwendung' für den Admin.
> Der Admin kann die Übersetzungen im Language-Management definieren,
nur für die Default-Language geht es nicht.
> Es ist ja nicht so, dass als Default Text EN statt DE (default) im FE angezeigt wird.
Sondern die neue Definition (vom Admin) wird gar nicht ausgegeben, dafür aber die Standarddefinition (auch DE). Hmm.

Der Admin soll nicht die labels für die 'default' Sprache definieren, sondern für die effektiv verwendete. Dies ist notwendig, weil diese Übersetzungen nicht ganz so funktionieren, wie es in TYPO3 gewohnt ist. Die Logik ist folgendermassen gedacht:
1. Gibt es eine benutzerdefinierte Übersetzung (in `typo3conf/tx_fecookies/UserdefinedLanguageLabels`, je nach `storageMode`)? Wenn Ja, anzeigen.
2. Gibt es eine Übersetzung in der aktuellen Sprache (`EXT:fe_cookies/Resources/Private/Language/userdefinedLabels.xlf`)? Wenn ja, anzeigen.
3. Zeige die 'default' Sprache von `EXT:fe_cookies/Resources/Private/Language/userdefinedLabels.xlf`

Wie Du siehst, gibt es nach 1. **keinen** fallback zur 'default' Sprache. Das ist absichtlich so gebaut, damit wir in 1. entscheiden können, ob es weiter geht oder nicht. Du kannst natürlich als Admin die 'default' Sprache (und/oder beliebige Übersetzungen) ändern, indem Du eine eigene(n) XML Datei(en) registrierst:

```php
$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['EXT:fe_cookies/Resources/Private/Language/userdefinedLabels.xlf'][] = 'EXT:myext/Resources/Private/Language/userdefinedLabels.xlf';
```

Siehe [das entsprechende Kapitel in der TYPO3 Core API Doku](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Internationalization/ManagingTranslations.html#xliff-translating-custom). Das steht ebenfalls in der Extension-Doku..

@Footrotflat: ist Dein Fragezeichen damit beantwortet?

**Comment by Footrotflat** [comment]
Hallo Christian

Besten Dank für deine Ausführungen.

Config PageTS:
Ja mit Config PageTS kenne ich mich nicht ganz so gut aus.
Ich mache die Definitionen jeweils in den ausgelagerten Dateien in der Extension.

ext_tables.php in der Extension fe_cookies:
Ja ich weiss, habs nur zum testen so angepasst.

'default' Sprache:
cool, danke.

Alle Fragen beantwortet.
Nochmals besten Dank und Gruss
Patrick
